# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='to_encode',
            field=models.BooleanField(default=True),
        ),
    ]
