# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codify', '0002_text_to_encode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='to_encode',
        ),
    ]
